use ::libc;
#[c2rust::header_src =
  "/home/nmavis/dev/gssapi-rs/code/src/include/com_err.h:43"]
pub mod com_err_h {
    /*
 * Copyright 1988, Student Information Processing Board of the
 * Massachusetts Institute of Technology.
 *
 * Copyright 1995 by Cygnus Support.
 *
 * For copyright and distribution info, see the documentation supplied
 * with this package.
 */
    /* Header file for common error description library. */
    #[c2rust::src_loc = "26:1"]
    pub type errcode_t = libc::c_long;
    #[derive(Copy, Clone)]
    #[repr(C)]
    #[c2rust::src_loc = "30:8"]
    pub struct error_table {
        pub msgs: *const *const libc::c_char,
        pub base: libc::c_long,
        pub n_msgs: libc::c_uint,
    }
    extern "C" {
        /*@modifies internalState@*/
        #[no_mangle]
        #[c2rust::src_loc = "57:1"]
        pub fn add_error_table(_: *const error_table) -> errcode_t;
    }
    /* ! defined(__COM_ERR_H) */
}
pub use self::com_err_h::{errcode_t, error_table, add_error_table};
/* Lclint doesn't handle null annotations on arrays
   properly, so we need this typedef in each
   generated .c file.  */
/*@-redef@*/
#[c2rust::src_loc = "19:1"]
pub type ncptr = *const libc::c_char;
/*@null@*/
/*@=redef@*/
#[c2rust::src_loc = "22:20"]
static mut text: [ncptr; 18] =
    [b"while getting policy info.\x00" as *const u8 as *const libc::c_char,
     b"while getting principal info.\x00" as *const u8 as *const libc::c_char,
     b"New passwords do not match - password not changed.\n\x00" as *const u8
         as *const libc::c_char,
     b"New password\x00" as *const u8 as *const libc::c_char,
     b"New password (again)\x00" as *const u8 as *const libc::c_char,
     b"You must type a password. Passwords must be at least one character long.\n\x00"
         as *const u8 as *const libc::c_char,
     b"yet no policy set!  Contact your system security administrator.\x00" as
         *const u8 as *const libc::c_char,
     b"Password changed.\n\x00" as *const u8 as *const libc::c_char,
     b"New password was found in a dictionary of possible passwords and\ntherefore may be easily guessed. Please choose another password.\nSee the kpasswd man page for help in choosing a good password.\x00"
         as *const u8 as *const libc::c_char,
     b"Password not changed.\x00" as *const u8 as *const libc::c_char,
     b"New password is too short.\nPlease choose a password which is at least %d characters long.\x00"
         as *const u8 as *const libc::c_char,
     b"New password does not have enough character classes.\nThe character classes are:\n\t- lower-case letters,\n\t- upper-case letters,\n\t- digits,\n\t- punctuation, and\n\t- all other characters (e.g., control characters).\nPlease choose a password with at least %d character classes.\x00"
         as *const u8 as *const libc::c_char,
     b"Password cannot be changed because it was changed too recently.\nPlease wait until %s before you change it.\nIf you need to change your password before then, contact your system\nsecurity administrator.\x00"
         as *const u8 as *const libc::c_char,
     b"New password was used previously. Please choose a different password.\x00"
         as *const u8 as *const libc::c_char,
     b"while trying to change password.\x00" as *const u8 as
         *const libc::c_char,
     b"while reading new password.\x00" as *const u8 as *const libc::c_char,
     b"mit-krb5\x00" as *const u8 as *const libc::c_char, 0 as ncptr];
#[no_mangle]
#[c2rust::src_loc = "45:26"]
pub static mut et_ovku_error_table: error_table =
    unsafe {
        {
            let mut init =
                error_table{msgs: text.as_ptr(),
                            base: -(1492553984 as libc::c_long),
                            n_msgs: 16 as libc::c_int as libc::c_uint,};
            init
        }
    };
/*
 * et-c-chpass_util_strings.c:
 * This file is automatically generated; please do not edit it.
 */
#[no_mangle]
#[c2rust::src_loc = "48:1"]
pub unsafe extern "C" fn initialize_ovku_error_table() 
 /*@modifies internalState@*/
 {
    add_error_table(&et_ovku_error_table);
}
