use ::libc;
#[c2rust::header_src =
  "/home/nmavis/dev/gssapi-rs/code/src/include/com_err.h:41"]
pub mod com_err_h {
    /*
 * Copyright 1988, Student Information Processing Board of the
 * Massachusetts Institute of Technology.
 *
 * Copyright 1995 by Cygnus Support.
 *
 * For copyright and distribution info, see the documentation supplied
 * with this package.
 */
    /* Header file for common error description library. */
    #[c2rust::src_loc = "26:1"]
    pub type errcode_t = libc::c_long;
    #[derive(Copy, Clone)]
    #[repr(C)]
    #[c2rust::src_loc = "30:8"]
    pub struct error_table {
        pub msgs: *const *const libc::c_char,
        pub base: libc::c_long,
        pub n_msgs: libc::c_uint,
    }
    extern "C" {
        /*@modifies internalState@*/
        #[no_mangle]
        #[c2rust::src_loc = "57:1"]
        pub fn add_error_table(_: *const error_table) -> errcode_t;
    }
    /* ! defined(__COM_ERR_H) */
}
pub use self::com_err_h::{errcode_t, error_table, add_error_table};
/* Lclint doesn't handle null annotations on arrays
   properly, so we need this typedef in each
   generated .c file.  */
/*@-redef@*/
#[c2rust::src_loc = "19:1"]
pub type ncptr = *const libc::c_char;
/*@null@*/
/*@=redef@*/
#[c2rust::src_loc = "22:20"]
static mut text: [ncptr; 16] =
    [b"No Error\x00" as *const u8 as *const libc::c_char,
     b"Principal or policy already exists\x00" as *const u8 as
         *const libc::c_char,
     b"Principal or policy does not exist\x00" as *const u8 as
         *const libc::c_char,
     b"Database not initialized\x00" as *const u8 as *const libc::c_char,
     b"Invalid policy name\x00" as *const u8 as *const libc::c_char,
     b"Invalid principal name\x00" as *const u8 as *const libc::c_char,
     b"Database inconsistency detected\x00" as *const u8 as
         *const libc::c_char,
     b"XDR encoding error\x00" as *const u8 as *const libc::c_char,
     b"Failure!\x00" as *const u8 as *const libc::c_char,
     b"Bad lock mode\x00" as *const u8 as *const libc::c_char,
     b"Cannot lock database\x00" as *const u8 as *const libc::c_char,
     b"Database not locked\x00" as *const u8 as *const libc::c_char,
     b"KADM5 administration database lock file missing\x00" as *const u8 as
         *const libc::c_char,
     b"Insufficient permission to lock file\x00" as *const u8 as
         *const libc::c_char,
     b"mit-krb5\x00" as *const u8 as *const libc::c_char, 0 as ncptr];
#[no_mangle]
#[c2rust::src_loc = "43:26"]
pub static mut et_adb_error_table: error_table =
    unsafe {
        {
            let mut init =
                error_table{msgs: text.as_ptr(),
                            base: 28810240 as libc::c_long,
                            n_msgs: 14 as libc::c_int as libc::c_uint,};
            init
        }
    };
/*
 * et-c-adb_err.c:
 * This file is automatically generated; please do not edit it.
 */
#[no_mangle]
#[c2rust::src_loc = "46:1"]
pub unsafe extern "C" fn initialize_adb_error_table() 
 /*@modifies internalState@*/
 {
    add_error_table(&et_adb_error_table);
}
