use ::libc;
#[c2rust::header_src =
  "/home/nmavis/dev/gssapi-rs/code/src/include/com_err.h:47"]
pub mod com_err_h {
    /*
 * Copyright 1988, Student Information Processing Board of the
 * Massachusetts Institute of Technology.
 *
 * Copyright 1995 by Cygnus Support.
 *
 * For copyright and distribution info, see the documentation supplied
 * with this package.
 */
    /* Header file for common error description library. */
    #[c2rust::src_loc = "26:1"]
    pub type errcode_t = libc::c_long;
    #[derive(Copy, Clone)]
    #[repr(C)]
    #[c2rust::src_loc = "30:8"]
    pub struct error_table {
        pub msgs: *const *const libc::c_char,
        pub base: libc::c_long,
        pub n_msgs: libc::c_uint,
    }
    extern "C" {
        /*@modifies internalState@*/
        #[no_mangle]
        #[c2rust::src_loc = "57:1"]
        pub fn add_error_table(_: *const error_table) -> errcode_t;
    }
    /* ! defined(__COM_ERR_H) */
}
pub use self::com_err_h::{errcode_t, error_table, add_error_table};
/* Lclint doesn't handle null annotations on arrays
   properly, so we need this typedef in each
   generated .c file.  */
/*@-redef@*/
#[c2rust::src_loc = "19:1"]
pub type ncptr = *const libc::c_char;
/*@null@*/
/*@=redef@*/
#[c2rust::src_loc = "22:20"]
static mut text: [ncptr; 22] =
    [b"No @ in SERVICE-NAME name string\x00" as *const u8 as
         *const libc::c_char,
     b"STRING-UID-NAME contains nondigits\x00" as *const u8 as
         *const libc::c_char,
     b"UID does not resolve to username\x00" as *const u8 as
         *const libc::c_char,
     b"Validation error\x00" as *const u8 as *const libc::c_char,
     b"Couldn\'t allocate gss_buffer_t data\x00" as *const u8 as
         *const libc::c_char,
     b"Message context invalid\x00" as *const u8 as *const libc::c_char,
     b"Buffer is the wrong size\x00" as *const u8 as *const libc::c_char,
     b"Credential usage type is unknown\x00" as *const u8 as
         *const libc::c_char,
     b"Unknown quality of protection specified\x00" as *const u8 as
         *const libc::c_char,
     b"Local host name could not be determined\x00" as *const u8 as
         *const libc::c_char,
     b"Hostname in SERVICE-NAME string could not be canonicalized\x00" as
         *const u8 as *const libc::c_char,
     b"Mechanism is incorrect\x00" as *const u8 as *const libc::c_char,
     b"Token header is malformed or corrupt\x00" as *const u8 as
         *const libc::c_char,
     b"Packet was replayed in wrong direction\x00" as *const u8 as
         *const libc::c_char,
     b"Token is missing data\x00" as *const u8 as *const libc::c_char,
     b"Token was reflected\x00" as *const u8 as *const libc::c_char,
     b"Received token ID does not match expected token ID\x00" as *const u8 as
         *const libc::c_char,
     b"The given credential\'s usage does not match the requested usage\x00"
         as *const u8 as *const libc::c_char,
     b"Storing of acceptor credentials is not supported by the mechanism\x00"
         as *const u8 as *const libc::c_char,
     b"Storing of non-default credentials is not supported by the mechanism\x00"
         as *const u8 as *const libc::c_char,
     b"mit-krb5\x00" as *const u8 as *const libc::c_char, 0 as ncptr];
#[no_mangle]
#[c2rust::src_loc = "49:26"]
pub static mut et_ggss_error_table: error_table =
    unsafe {
        {
            let mut init =
                error_table{msgs: text.as_ptr(),
                            base: -(2045022976 as libc::c_long),
                            n_msgs: 20 as libc::c_int as libc::c_uint,};
            init
        }
    };
/*
 * et-c-gssapi_err_generic.c:
 * This file is automatically generated; please do not edit it.
 */
#[no_mangle]
#[c2rust::src_loc = "52:1"]
pub unsafe extern "C" fn initialize_ggss_error_table() 
 /*@modifies internalState@*/
 {
    add_error_table(&et_ggss_error_table);
}
